{
 "title": "Glances",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values with key=\"hostname\""
   },
   {
    "name": "container",
    "query": "show tag values with key=\"name\""
   },
   {
    "name": "interface",
    "query": "show tag values with key=\"interface_name\""
   },
   {
    "name": "disk",
    "query": "show tag values with key=\"disk_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Core",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "column": "cpucore",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "load",
     "query": "SELECT mean(\"cpucore\") FROM \"$host.load\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "cpucore" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "1min",
     "column": "min1",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "load",
     "query": "SELECT mean(\"min1\") FROM \"$host.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "min1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "randomWalk('random walk')"
    },
    {
     "alias": "5mins",
     "column": "min5",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "load",
     "query": "SELECT mean(\"min5\") FROM \"$host.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "min5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "15mins",
     "column": "min15",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "load",
     "query": "SELECT mean(\"min15\") FROM \"$host.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "min15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "processcount",
     "query": "SELECT mean(\"total\") FROM \"$host.processcount\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "series": "processcount",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "User",
     "column": "user",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"user\") FROM \"$host.cpu\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "System",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"$host.cpu\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "IoWait",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"iowait\") FROM \"$host.cpu\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used\") FROM \"mem\" WHERE (\"hostname\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max",
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"total\") FROM \"mem\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$interface network interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "In",
     "column": "enp0s25.rx",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "$host.network",
     "query": "SELECT mean(\"rx\")/mean(\"time_since_update\")*8 FROM \"network\" WHERE (\"hostname\" =~ /^$host$/) AND (\"interface_name\" =~ /^$interface$/) AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "eth0.rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "network"
    },
    {
     "alias": "Out",
     "column": "eth0.tx*-1",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "$host.network",
     "query": "SELECT mean(\"tx\")/mean(\"time_since_update\")*-8 FROM \"network\" WHERE (\"hostname\" =~ /^$host$/) AND (\"interface_name\" =~ /^$interface$/) AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "eth0.tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "network"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "$host.memswap",
     "query": "SELECT mean(\"used\") FROM \"memswap\" WHERE (\"hostname\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "memswap"
    },
    {
     "alias": "Max",
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "$host.memswap",
     "query": "SELECT mean(\"total\") FROM \"memswap\" WHERE (\"hostname\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "memswap"
    }
   ]
  },
  {
   "title": "$disk disk IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Read",
     "column": "sda2.read_bytes",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$host.diskio",
     "query": "SELECT mean(\"read_bytes\")/mean(\"time_since_update\") FROM \"diskio\" WHERE (\"hostname\" =~ /^$host$/) AND  (\"disk_name\" =~ /^$disk$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "sda2.read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "diskio"
    },
    {
     "alias": "Write",
     "column": "sda2.write_bytes",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$host.diskio",
     "query": "SELECT mean(\"write_bytes\")/mean(\"time_since_update\") FROM \"diskio\" WHERE (\"hostname\" =~ /^$host$/) AND  (\"disk_name\" =~ /^$disk$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "sda2.write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "diskio"
    }
   ]
  },
  {
   "title": "/ Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Used",
     "column": "\"/.used\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fs",
     "query": "SELECT mean(\"/.used\") FROM \"$host.fs\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs",
     "tags": [
      { "key": "mnt_point", "operator": "=", "value": "/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max",
     "column": "\"/.size\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fs",
     "query": "SELECT mean(\"/.size\") FROM \"$host.fs\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs",
     "tags": [
      { "key": "mnt_point", "operator": "=", "value": "/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "/ used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "column": "\"/.percent\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fs",
     "query": "SELECT mean(\"/.percent\") FROM \"$host.fs\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs",
     "tags": [
      { "key": "mnt_point", "operator": "=", "value": "/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "/boot used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "column": "\"/home.percent\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fs",
     "query": "SELECT mean(\"percent\") FROM \"fs\" WHERE (\"hostname\" =~ /^$host$/) AND (\"mnt_point\" = '/boot') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs",
     "tags": [
      { "key": "mnt_point", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^SensorType.CPU_TEMP$/" }
     ]
    }
   ]
  },
  {
   "title": "FAN speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "alias": "$tag_label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^SensorType.FAN_SPEED$/" }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$container container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "CPU%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "containers",
     "query": "SELECT mean(\"cpu_percent\") FROM \"$host.docker\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "MEM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "containers",
     "query": "SELECT mean(\"cpu_percent\") FROM \"$host.docker\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}